DATA_DIR = './data'
TRAIN_FILE = 'train.csv'
TEST_FILE = 'test.csv'
TRAIN_PROC_FILE = 'train_processed.csv'
TEST_PROC_FILE = 'test_processed.csv'
LINEAR_REG_PRED_FILE = 'linear_regression.csv'
LOG_REG_PRED_FILE = 'log_regression.csv'
NN_PRED_FILE = 'nn_pred.csv'
DEC_TREE_PRED_FILE = 'dec_tree_pred.csv'
EXTRA_TREE_PRED_FILE = 'extra_tree_pred.csv'
RF_PRED_FILE = 'rf_pred.csv'

MODEL_DIR = './models'
SEX_ENC_PKL = 'sex_enc_map.pkl'
TITLE_ENC_PKL = 'title_enc_map.pkl'
EMBARKED_ENC_PKL = 'embarked_enc_map.pkl'
NN_CKPT = 'titanic.ckpt'

